<a href="https://colab.research.google.com/github/hafizdabo/hamoye-fork-project/blob/main/importing_numpy_convention.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = [6, 7, 8, 9]
print(type(arr))

<class 'list'>


In [ ]:
a = np.array(arr)
print(type(a))
print(a.shape)
print(a.dtype)

<class 'numpy.ndarray'>
(4,)
int64


In [ ]:
#get the dimwnsion of *a with ndim
print(a.ndim)

1


In [1]:
import numpy as np

In [2]:
arr = [6, 7, 8, 9]
print(type(arr))

<class 'list'>


In [3]:
a = np.array(arr)
print(type(a))
print(a.shape)
print(a.dtype)

<class 'numpy.ndarray'>
(4,)
int64


In [4]:
#get the dimension of a with ndim
print(a.ndim)

1


In [9]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [11]:
print(b.ndim)
b.shape

2


(2, 3)

## In-built Functions that can be used to initialize numpy

In [13]:
# a 2x3 array with random values
np.random.random((2, 3))

array([[0.39450146, 0.35961126, 0.98778981],
       [0.83136149, 0.0181359 , 0.07296334]])

In [14]:
# a 2x3 array of zeros
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# a 2x3 array of ones
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
# a 3x3 identity matrix 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Intra-operability of arrays and scalars

In [19]:
c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])


In [20]:
c + d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [21]:
c * d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [22]:
5/d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [23]:
c**2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

## Indexing with arrays and using arrays for data processing

In [26]:
# we can access the elements in the example arrays above by indexing like lists in Python such as:
a[0]


6

In [27]:
a[3]


9

In [28]:
b[0, 0]


1

In [29]:
b[1, 2]


6

In [30]:

c[0, 1]

8.0

In [31]:
# elements in arrays can also be retrieved by slicing rows and columns 
d[1, 0:2]

array([9., 8.])

In [32]:
e = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])

In [33]:
#slicing
e[:3, :2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [36]:
e[e>15]

array([16, 17, 18])